export const STATUS = {
  IDLE: "IDLE",
  LOADING: "LOADING",
  LOADED: "LOADED",
  ERROR: "ERROR",
  SUBMITTING_PAYMENT_INTENT: "SUBMITTING_PAYMENT_INTENT",
  LOADING_CARDS: "LOADING_CARDS",
  SUBMITTING: "SUBMITTING",
};

export const USER_ROLE = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  USER: "USER",
};

export const BACKEND_BASE_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
export const API_BASE_URL = `${BACKEND_BASE_URL}/api`;
